########## Admin API #######
### Root Domain
GET http://localhost:8000
### Get Admin API 
GET http://localhost:8000/api/v1/admin

### POST Admin API 
POST http://localhost:8000/api/v1/admin
Content-Type: application/json

{
  "fName":"admin",
  "lName":"admin",
  "dob":"11/02/2022",
  "email":"admin@admin.com",
  "userPassword":"apple123",
  "address":"34 Batman Way",
  "phone":"0420420735"
}

### POST admin verification API 

POST http://localhost:8000/api/v1/admin/verify-email
Content-Type: application/json

{
 "emailValidationCode":"1ccf1f0c-4ff3-4172-8bc5-8d432b7e93ef",
 "email":"kalubhaiya@gmail.com"
}

### Login Admin verification API 
POST http://localhost:8000/api/v1/admin/login
Content-Type: application/json

{

  "email":"callmesamip@gmail.com",
  "userPassword":"123Samip"
}


### PATCH Admin API 
PATCH http://localhost:8000/api/v1/admin



######## Category Routers

###POST Category
POST  http://localhost:8000/api/v1/categories
Content-Type: application/json

{
  "parentCatId":"62cf84451619dc2c13b2505c",
  "catName":" Water Filter "
}
###GET CATEGORY 
GET http://localhost:8000/api/v1/categories

###UPDATE  CATEGORY 
PATCH http://localhost:8000/api/v1/categories
Content-Type: application/json

{
  "_id":"62cf84a43463ad9844ed93c3",
  "status":"inactive"
}



###Product

POST http://localhost:8000/api/v1/products
Content-Type: application/json

{

		"name": "C-Shaped Sofa",
		"SKU":"c-shaped-frontends",
		"description": "Lorem ipsum ipsum lorem",
		"quantity":100,
		"price": 3000,
		"salePrice": 0,
		"saleDate":null
}